'use client';

import { useEffect, useState } from 'react';
import { Button, Group, Modal, Stack, TextInput, Textarea } from '@mantine/core';
import { notifications } from '@mantine/notifications';
import { useMutation } from '@tanstack/react-query';
import { api } from '@/api';
import type { Interview, ModalProps } from './application-types';

export function MeetingNotesModal({
  interview,
  opened,
  onClose,
  onSaved,
}: ModalProps & { interview: Interview }) {
  const [notes, setNotes] = useState(interview.meetingNotes ?? '');
  const [source, setSource] = useState(interview.meetingNotesSource ?? '');
  useEffect(() => {
    if (!opened) return;
    setNotes(interview.meetingNotes ?? '');
    setSource(interview.meetingNotesSource ?? '');
  }, [interview.meetingNotes, interview.meetingNotesSource, opened]);
  const mutation = useMutation({
    mutationFn: () =>
      api.put(`/api/interviews/${interview.id}/meeting-notes`, {
        notes,
        source: source.trim() || null,
      }),
    onSuccess: () => {
      onSaved();
      onClose();
      notifications.show({ color: 'teal', message: 'Meeting notes saved' });
    },
    onError: (error: Error) => notifications.show({ color: 'red', message: error.message }),
  });
  return (
    <Modal opened={opened} onClose={onClose} title="Meeting notes" size="xl">
      <Stack>
        <TextInput
          label="Generated by"
          description="For example: Fireflies, Fathom, Otter, or manual import"
          value={source}
          maxLength={120}
          onChange={(event) => setSource(event.currentTarget.value)}
        />
        <Textarea
          label="Notes"
          description="Paste the meeting assistant's notes or transcript here."
          autosize
          minRows={14}
          maxRows={24}
          maxLength={100_000}
          value={notes}
          onChange={(event) => setNotes(event.currentTarget.value)}
        />
        <Group justify="flex-end">
          <Button variant="default" onClick={onClose}>
            Cancel
          </Button>
          <Button
            disabled={!notes.trim()}
            loading={mutation.isPending}
            onClick={() => mutation.mutate()}
          >
            Save notes
          </Button>
        </Group>
      </Stack>
    </Modal>
  );
}
